import { Nunito } from "next/font/google";
import { Header } from "@/components/shared";
import type { Metadata } from "next";
import "./globals.css";

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Next Pizza | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className}  antialiased w-svw bg-[#FFBF9B] p-4`}
      >
        <main className="bg-white rounded-3xl shadow-lg">
          <Header />

          {children}
        </main>
      </body>
    </html>
  );
}
